/// KelpyShark → C Code Generator
///
/// Transpiles a KelpyShark AST into C source code.
/// The generated C can be compiled with GCC or Clang to produce native binaries.
///
/// Strategy:
///   - All KelpyShark values are represented as a tagged union (`KsValue`).
///   - A small runtime header is emitted at the top.
///   - Statements map to C statements; expressions map to C expressions.

use crate::ast::*;

/// Generate a complete C source file from a KelpyShark Program AST.
pub fn generate(program: &Program) -> String {
    let mut gen = CGenerator::new();
    gen.emit_program(program);
    gen.output
}

struct CGenerator {
    output: String,
    indent: usize,
}

impl CGenerator {
    fn new() -> Self {
        CGenerator {
            output: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, text: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&format!("{}{}\n", indent_str, text));
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    // ── Program generation ──

    fn emit_program(&mut self, program: &Program) {
        self.emit_runtime_header();
        self.blank();

        // Forward-declare user functions
        for stmt in &program.statements {
            if let Statement::FunctionDef { name, params, .. } = stmt {
                let param_list: Vec<String> = params.iter().map(|_| "KsValue".to_string()).collect();
                self.line(&format!(
                    "KsValue ks_{}({});",
                    name,
                    param_list.join(", ")
                ));
            }
        }
        self.blank();

        // Emit function definitions before main
        for stmt in &program.statements {
            if let Statement::FunctionDef { .. } = stmt {
                self.emit_statement(stmt);
                self.blank();
            }
        }

        // Emit main
        self.line("int main(void) {");
        self.indent += 1;

        for stmt in &program.statements {
            if let Statement::FunctionDef { .. } = stmt {
                continue; // Already emitted above
            }
            self.emit_statement(stmt);
        }

        self.line("return 0;");
        self.indent -= 1;
        self.line("}");
    }

    fn emit_runtime_header(&mut self) {
        self.line("/* Generated by KelpyShark Compiler v0.1.0 */");
        self.line("#include <stdio.h>");
        self.line("#include <stdlib.h>");
        self.line("#include <string.h>");
        self.line("#include <math.h>");
        self.blank();
        self.line("/* KelpyShark runtime value type */");
        self.line("typedef enum { KS_NUMBER, KS_STRING, KS_BOOL, KS_NULL } KsType;");
        self.blank();
        self.line("typedef struct {");
        self.indent += 1;
        self.line("KsType type;");
        self.line("union {");
        self.indent += 1;
        self.line("double number;");
        self.line("char* string;");
        self.line("int boolean;");
        self.indent -= 1;
        self.line("} data;");
        self.indent -= 1;
        self.line("} KsValue;");
        self.blank();
        // Constructor helpers
        self.line("static KsValue ks_num(double n) { KsValue v; v.type = KS_NUMBER; v.data.number = n; return v; }");
        self.line("static KsValue ks_str(const char* s) { KsValue v; v.type = KS_STRING; v.data.string = strdup(s); return v; }");
        self.line("static KsValue ks_bool(int b) { KsValue v; v.type = KS_BOOL; v.data.boolean = b; return v; }");
        self.line("static KsValue ks_null(void) { KsValue v; v.type = KS_NULL; v.data.number = 0; return v; }");
        self.blank();
        // Print helper
        self.line("static void ks_print(KsValue v) {");
        self.indent += 1;
        self.line("switch (v.type) {");
        self.indent += 1;
        self.line("case KS_NUMBER:");
        self.indent += 1;
        self.line("if (v.data.number == (int)v.data.number) printf(\"%d\\n\", (int)v.data.number);");
        self.line("else printf(\"%g\\n\", v.data.number);");
        self.line("break;");
        self.indent -= 1;
        self.line("case KS_STRING: printf(\"%s\\n\", v.data.string); break;");
        self.line("case KS_BOOL: printf(\"%s\\n\", v.data.boolean ? \"true\" : \"false\"); break;");
        self.line("case KS_NULL: printf(\"null\\n\"); break;");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();
        // Arithmetic / concat helpers
        self.line("static KsValue ks_add(KsValue a, KsValue b) {");
        self.indent += 1;
        self.line("if (a.type == KS_NUMBER && b.type == KS_NUMBER) return ks_num(a.data.number + b.data.number);");
        self.line("if (a.type == KS_STRING && b.type == KS_STRING) {");
        self.indent += 1;
        self.line("char* buf = malloc(strlen(a.data.string) + strlen(b.data.string) + 1);");
        self.line("strcpy(buf, a.data.string); strcat(buf, b.data.string);");
        self.line("KsValue v; v.type = KS_STRING; v.data.string = buf; return v;");
        self.indent -= 1;
        self.line("}");
        self.line("/* string + number coercion */");
        self.line("if (a.type == KS_STRING && b.type == KS_NUMBER) {");
        self.indent += 1;
        self.line("char tmp[64]; if (b.data.number == (int)b.data.number) snprintf(tmp, 64, \"%d\", (int)b.data.number); else snprintf(tmp, 64, \"%g\", b.data.number);");
        self.line("char* buf = malloc(strlen(a.data.string) + strlen(tmp) + 1);");
        self.line("strcpy(buf, a.data.string); strcat(buf, tmp);");
        self.line("KsValue v; v.type = KS_STRING; v.data.string = buf; return v;");
        self.indent -= 1;
        self.line("}");
        self.line("if (a.type == KS_NUMBER && b.type == KS_STRING) {");
        self.indent += 1;
        self.line("char tmp[64]; if (a.data.number == (int)a.data.number) snprintf(tmp, 64, \"%d\", (int)a.data.number); else snprintf(tmp, 64, \"%g\", a.data.number);");
        self.line("char* buf = malloc(strlen(tmp) + strlen(b.data.string) + 1);");
        self.line("strcpy(buf, tmp); strcat(buf, b.data.string);");
        self.line("KsValue v; v.type = KS_STRING; v.data.string = buf; return v;");
        self.indent -= 1;
        self.line("}");
        self.line("return ks_null();");
        self.indent -= 1;
        self.line("}");
        self.blank();
        self.line("static KsValue ks_sub(KsValue a, KsValue b) { return ks_num(a.data.number - b.data.number); }");
        self.line("static KsValue ks_mul(KsValue a, KsValue b) { return ks_num(a.data.number * b.data.number); }");
        self.line("static KsValue ks_div(KsValue a, KsValue b) { return ks_num(a.data.number / b.data.number); }");
        self.line("static KsValue ks_mod(KsValue a, KsValue b) { return ks_num(fmod(a.data.number, b.data.number)); }");
        self.blank();
        self.line("static KsValue ks_eq(KsValue a, KsValue b) {");
        self.indent += 1;
        self.line("if (a.type != b.type) return ks_bool(0);");
        self.line("if (a.type == KS_NUMBER) return ks_bool(a.data.number == b.data.number);");
        self.line("if (a.type == KS_STRING) return ks_bool(strcmp(a.data.string, b.data.string) == 0);");
        self.line("if (a.type == KS_BOOL) return ks_bool(a.data.boolean == b.data.boolean);");
        self.line("return ks_bool(1);");
        self.indent -= 1;
        self.line("}");
        self.line("static KsValue ks_neq(KsValue a, KsValue b) { return ks_bool(!ks_eq(a, b).data.boolean); }");
        self.line("static KsValue ks_lt(KsValue a, KsValue b) { return ks_bool(a.data.number < b.data.number); }");
        self.line("static KsValue ks_le(KsValue a, KsValue b) { return ks_bool(a.data.number <= b.data.number); }");
        self.line("static KsValue ks_gt(KsValue a, KsValue b) { return ks_bool(a.data.number > b.data.number); }");
        self.line("static KsValue ks_ge(KsValue a, KsValue b) { return ks_bool(a.data.number >= b.data.number); }");
        self.blank();
        self.line("static int ks_truthy(KsValue v) {");
        self.indent += 1;
        self.line("if (v.type == KS_NULL) return 0;");
        self.line("if (v.type == KS_BOOL) return v.data.boolean;");
        self.line("if (v.type == KS_NUMBER) return v.data.number != 0.0;");
        self.line("if (v.type == KS_STRING) return strlen(v.data.string) > 0;");
        self.line("return 1;");
        self.indent -= 1;
        self.line("}");
    }

    // ── Statement emission ──

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Assignment { name, value, .. } => {
                let expr = self.emit_expr(value);
                self.line(&format!("KsValue {} = {};", name, expr));
            }
            Statement::FunctionDef {
                name,
                params,
                body,
                ..
            } => {
                let param_list: Vec<String> = params
                    .iter()
                    .map(|p| format!("KsValue {}", p))
                    .collect();
                self.line(&format!(
                    "KsValue ks_{}({}) {{",
                    name,
                    param_list.join(", ")
                ));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.line("return ks_null();");
                self.indent -= 1;
                self.line("}");
            }
            Statement::If {
                condition,
                then_body,
                else_body,
                ..
            } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("if (ks_truthy({})) {{", cond));
                self.indent += 1;
                for s in then_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::While {
                condition, body, ..
            } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("while (ks_truthy({})) {{", cond));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                // Re-evaluate condition variable if it changed
                self.indent -= 1;
                self.line("}");
            }
            Statement::Return { value, .. } => {
                let val = match value {
                    Some(expr) => self.emit_expr(expr),
                    None => "ks_null()".to_string(),
                };
                self.line(&format!("return {};", val));
            }
            Statement::Print { value, .. } => {
                let expr = self.emit_expr(value);
                self.line(&format!("ks_print({});", expr));
            }
            Statement::ExprStatement { expr, .. } => {
                let e = self.emit_expr(expr);
                self.line(&format!("{};", e));
            }
            Statement::Import { module, .. } => {
                self.line(&format!("/* import {} */", module));
            }
            Statement::For { .. } => {
                self.line("/* TODO: for loop C codegen */");
            }
            // New statements — stub out for now
            Statement::Break { .. } => self.line("break;"),
            Statement::Continue { .. } => self.line("continue;"),
            Statement::Throw { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("ks_throw({});", v));
            }
            Statement::TryCatch { .. }
            | Statement::CompoundAssignment { .. }
            | Statement::ClassDef { .. } => {
                self.line("/* TODO: codegen for this statement */");
            }
        }
    }

    // ── Expression emission ──

    fn emit_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::NumberLiteral { value, .. } => {
                if *value == (*value as i64) as f64 {
                    format!("ks_num({}.0)", *value as i64)
                } else {
                    format!("ks_num({})", value)
                }
            }
            Expr::StringLiteral { value, .. } => {
                format!("ks_str(\"{}\")", value.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::BooleanLiteral { value, .. } => {
                format!("ks_bool({})", if *value { 1 } else { 0 })
            }
            Expr::Identifier { name, .. } => name.clone(),
            Expr::BinaryOp {
                left, op, right, ..
            } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                match op {
                    BinaryOperator::Add => format!("ks_add({}, {})", l, r),
                    BinaryOperator::Subtract => format!("ks_sub({}, {})", l, r),
                    BinaryOperator::Multiply => format!("ks_mul({}, {})", l, r),
                    BinaryOperator::Divide => format!("ks_div({}, {})", l, r),
                    BinaryOperator::Modulo => format!("ks_mod({}, {})", l, r),
                    BinaryOperator::Equal => format!("ks_eq({}, {})", l, r),
                    BinaryOperator::NotEqual => format!("ks_neq({}, {})", l, r),
                    BinaryOperator::LessThan => format!("ks_lt({}, {})", l, r),
                    BinaryOperator::LessEqual => format!("ks_le({}, {})", l, r),
                    BinaryOperator::GreaterThan => format!("ks_gt({}, {})", l, r),
                    BinaryOperator::GreaterEqual => format!("ks_ge({}, {})", l, r),
                    BinaryOperator::And => {
                        format!("ks_bool(ks_truthy({}) && ks_truthy({}))", l, r)
                    }
                    BinaryOperator::Or => {
                        format!("ks_bool(ks_truthy({}) || ks_truthy({}))", l, r)
                    }
                }
            }
            Expr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand);
                match op {
                    UnaryOperator::Negate => format!("ks_num(-({}).data.number)", o),
                    UnaryOperator::Not => format!("ks_bool(!ks_truthy({}))", o),
                }
            }
            Expr::FunctionCall { callee, args, .. } => {
                let func_name = match callee.as_ref() {
                    Expr::Identifier { name, .. } => format!("ks_{}", name),
                    _ => "/* unknown call */".to_string(),
                };
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("{}({})", func_name, arg_strs.join(", "))
            }
            Expr::StringInterpolation { parts, .. } => {
                // Build through concatenation
                let mut result = String::from("ks_str(\"\")");
                for part in parts {
                    match part {
                        StringPart::Literal(s) => {
                            result = format!(
                                "ks_add({}, ks_str(\"{}\"))",
                                result,
                                s.replace('\\', "\\\\").replace('"', "\\\"")
                            );
                        }
                        StringPart::Expression(expr) => {
                            let e = self.emit_expr(expr);
                            result = format!("ks_add({}, {})", result, e);
                        }
                    }
                }
                result
            }
            Expr::Index { .. } => "/* TODO: index access */ks_null()".to_string(),
            Expr::MemberAccess { .. } => "/* TODO: member access */ks_null()".to_string(),
            Expr::ListLiteral { .. } => "/* TODO: list literal */ks_null()".to_string(),
            Expr::DictLiteral { .. } => "/* TODO: dict literal */ks_null()".to_string(),
            Expr::NullLiteral { .. } => "ks_null()".to_string(),
            Expr::MethodCall { .. } => "/* TODO: method call */ks_null()".to_string(),
            Expr::New { .. } => "/* TODO: new expression */ks_null()".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen_c(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let program = parser.parse().unwrap();
        generate(&program)
    }

    #[test]
    fn test_c_print_string() {
        let c = gen_c(r#"print "Hello""#);
        assert!(c.contains("ks_print(ks_str(\"Hello\"))"));
        assert!(c.contains("int main(void)"));
    }

    #[test]
    fn test_c_assignment() {
        let c = gen_c("x = 42");
        assert!(c.contains("KsValue x = ks_num(42.0)"));
    }

    #[test]
    fn test_c_function_def() {
        let c = gen_c("def add(a, b) {\n  return a + b\n}");
        assert!(c.contains("KsValue ks_add(KsValue a, KsValue b)"));
        assert!(c.contains("return ks_add(a, b)"));
    }

    #[test]
    fn test_c_if_statement() {
        let c = gen_c("if x >= 5 {\n  print x\n}");
        assert!(c.contains("if (ks_truthy(ks_ge(x, ks_num(5.0))))"));
    }

    #[test]
    fn test_c_binary_ops() {
        let c = gen_c("x = 1 + 2");
        assert!(c.contains("ks_add(ks_num(1.0), ks_num(2.0))"));
    }

    #[test]
    fn test_c_includes() {
        let c = gen_c("print 1");
        assert!(c.contains("#include <stdio.h>"));
        assert!(c.contains("#include <stdlib.h>"));
        assert!(c.contains("#include <string.h>"));
    }
}
