/// KelpyShark → C# Code Generator
///
/// Transpiles a KelpyShark AST into C# source code.
///
/// Strategy:
///   - All KelpyShark values are represented as `object` (C#'s universal base type).
///   - The `dynamic` keyword is used for arithmetic/comparisons to avoid casts.
///   - A static runtime helpers region is emitted at the top of the class.
///   - User-defined functions become private static methods on `Program`.
///   - The top-level program runs in `Main(string[] args)`.
///   - KelpyShark classes become nested static classes.

use crate::ast::*;

/// Generate a complete C# source file from a KelpyShark Program AST.
pub fn generate(program: &Program) -> String {
    let mut gen = CsGenerator::new();
    gen.emit_program(program);
    gen.output
}

struct CsGenerator {
    output: String,
    indent: usize,
}

impl CsGenerator {
    fn new() -> Self {
        CsGenerator {
            output: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, text: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&format!("{}{}\n", indent_str, text));
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    // ── Program ──────────────────────────────────────────────

    fn emit_program(&mut self, program: &Program) {
        self.line("// Generated by KelpyShark Compiler v0.2.0");
        self.line("using System;");
        self.line("using System.Collections.Generic;");
        self.line("using System.Linq;");
        self.blank();
        self.line("class Program {");
        self.indent += 1;

        self.emit_runtime_helpers();
        self.blank();

        // Inner class definitions
        for stmt in &program.statements {
            if let Statement::ClassDef { .. } = stmt {
                self.emit_statement(stmt);
                self.blank();
            }
        }

        // User-defined functions
        for stmt in &program.statements {
            if let Statement::FunctionDef { .. } = stmt {
                self.emit_statement(stmt);
                self.blank();
            }
        }

        // Entry point
        self.line("static void Main(string[] args) {");
        self.indent += 1;
        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef { .. } | Statement::ClassDef { .. } => continue,
                _ => self.emit_statement(stmt),
            }
        }
        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
    }

    // ── Runtime helpers ───────────────────────────────────────

    fn emit_runtime_helpers(&mut self) {
        // Print
        self.line("#region Runtime");
        self.line("static void KsPrint(object v) {");
        self.indent += 1;
        self.line("if (v is double d)");
        self.indent += 1;
        self.line("Console.WriteLine(d == Math.Floor(d) && !double.IsInfinity(d) ? ((long)d).ToString() : d.ToString());");
        self.indent -= 1;
        self.line("else Console.WriteLine(v ?? \"null\");");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Truthiness
        self.line("static bool KsTruthy(object v) {");
        self.indent += 1;
        self.line("if (v == null) return false;");
        self.line("if (v is bool b) return b;");
        self.line("if (v is double d) return d != 0.0;");
        self.line("if (v is string s) return s.Length > 0;");
        self.line("if (v is List<object> l) return l.Count > 0;");
        self.line("if (v is Dictionary<object,object> dict) return dict.Count > 0;");
        self.line("return true;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Add / concat
        self.line("static object KsAdd(object a, object b) {");
        self.indent += 1;
        self.line("if (a is double da && b is double db) return da + db;");
        self.line("return KsStr(a) + KsStr(b);");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Arithmetic
        self.line("static object KsSub(object a, object b) => (double)a - (double)b;");
        self.line("static object KsMul(object a, object b) => (double)a * (double)b;");
        self.line("static object KsDiv(object a, object b) => (double)a / (double)b;");
        self.line("static object KsMod(object a, object b) => (double)a % (double)b;");
        self.blank();

        // Comparison
        self.line("static object KsEq(object a, object b) {");
        self.indent += 1;
        self.line("if (a == null && b == null) return true;");
        self.line("if (a == null || b == null) return false;");
        self.line("return a.Equals(b);");
        self.indent -= 1;
        self.line("}");
        self.line("static object KsNeq(object a, object b) => !(bool)KsEq(a, b);");
        self.line("static object KsLt(object a, object b)  => (double)a < (double)b;");
        self.line("static object KsLe(object a, object b)  => (double)a <= (double)b;");
        self.line("static object KsGt(object a, object b)  => (double)a > (double)b;");
        self.line("static object KsGe(object a, object b)  => (double)a >= (double)b;");
        self.blank();

        // Type helpers
        self.line("static string KsStr(object v) {");
        self.indent += 1;
        self.line("if (v == null) return \"null\";");
        self.line("if (v is double d) return d == Math.Floor(d) && !double.IsInfinity(d) ? ((long)d).ToString() : d.ToString();");
        self.line("return v.ToString();");
        self.indent -= 1;
        self.line("}");
        self.blank();

        self.line("static object KsType(object v) {");
        self.indent += 1;
        self.line("if (v == null) return \"null\";");
        self.line("if (v is double) return \"number\";");
        self.line("if (v is string) return \"string\";");
        self.line("if (v is bool) return \"boolean\";");
        self.line("if (v is List<object>) return \"list\";");
        self.line("if (v is Dictionary<object,object>) return \"dict\";");
        self.line("return \"object\";");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // len()
        self.line("static object KsLen(object v) {");
        self.indent += 1;
        self.line("if (v is string s) return (double)s.Length;");
        self.line("if (v is List<object> l) return (double)l.Count;");
        self.line("if (v is Dictionary<object,object> d) return (double)d.Count;");
        self.line("throw new Exception(\"len() not supported for \" + KsType(v));");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // push()
        self.line("static object KsPush(object list, object val) {");
        self.indent += 1;
        self.line("var copy = new List<object>((List<object>)list) { val };");
        self.line("return copy;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Index access
        self.line("static object KsIndex(object obj, object idx) {");
        self.indent += 1;
        self.line("if (obj is List<object> l) return l[(int)(double)idx];");
        self.line("if (obj is Dictionary<object,object> d) return d[idx];");
        self.line("if (obj is string s) return s[(int)(double)idx].ToString();");
        self.line("throw new Exception(\"Cannot index \" + KsType(obj));");
        self.indent -= 1;
        self.line("}");
        self.line("#endregion");
    }

    // ── Statements ────────────────────────────────────────────

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Assignment { name, value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("object {} = {};", name, v));
            }
            Statement::CompoundAssignment { name, op, value, .. } => {
                let v = self.emit_expr(value);
                let helper = match op {
                    CompoundOp::Add      => "KsAdd",
                    CompoundOp::Subtract => "KsSub",
                    CompoundOp::Multiply => "KsMul",
                    CompoundOp::Divide   => "KsDiv",
                };
                self.line(&format!("{} = {}({}, {});", name, helper, name, v));
            }
            Statement::FunctionDef { name, params, body, .. } => {
                let param_list = params
                    .iter()
                    .map(|p| format!("object {}", p))
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(&format!("static object Ks_{}({}) {{", name, param_list));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.line("return null;");
                self.indent -= 1;
                self.line("}");
            }
            Statement::If { condition, then_body, else_body, .. } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("if (KsTruthy({})) {{", cond));
                self.indent += 1;
                for s in then_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::While { condition, body, .. } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("while (KsTruthy({})) {{", cond));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::For { variable, iterable, body, .. } => {
                let iter = self.emit_expr(iterable);
                self.line(&format!("foreach (object {} in (System.Collections.IEnumerable)({})) {{", variable, iter));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::Return { value, .. } => {
                let val = match value {
                    Some(expr) => self.emit_expr(expr),
                    None => "null".to_string(),
                };
                self.line(&format!("return {};", val));
            }
            Statement::Break { .. }    => self.line("break;"),
            Statement::Continue { .. } => self.line("continue;"),
            Statement::Print { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("KsPrint({});", v));
            }
            Statement::ExprStatement { expr, .. } => {
                let e = self.emit_expr(expr);
                self.line(&format!("{};", e));
            }
            Statement::Import { module, .. } => {
                self.line(&format!("// using {}; // KelpyShark import", module));
            }
            Statement::Throw { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("throw new Exception(KsStr({}));", v));
            }
            Statement::TryCatch { try_body, catch_var, catch_body, .. } => {
                self.line("try {");
                self.indent += 1;
                for s in try_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line(&format!("}} catch (Exception _ex_{}) {{", catch_var));
                self.indent += 1;
                self.line(&format!(
                    "object {} = (object)(_ex_{}.Message ?? _ex_{}.ToString());",
                    catch_var, catch_var, catch_var
                ));
                for s in catch_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::ClassDef { name, methods, .. } => {
                self.line(&format!("class {} {{", name));
                self.indent += 1;
                for m in methods {
                    self.emit_statement(m);
                }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    // ── Expressions ───────────────────────────────────────────

    fn emit_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::NumberLiteral { value, .. } => {
                if *value == (*value as i64) as f64 {
                    format!("(double){}", *value as i64)
                } else {
                    format!("(double){}", value)
                }
            }
            Expr::StringLiteral { value, .. } => {
                format!("\"{}\"",
                    value.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::BooleanLiteral { value, .. } => {
                if *value { "true".to_string() } else { "false".to_string() }
            }
            Expr::NullLiteral { .. } => "null".to_string(),
            Expr::Identifier { name, .. } => name.clone(),
            Expr::BinaryOp { left, op, right, .. } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                match op {
                    BinaryOperator::Add        => format!("KsAdd({}, {})", l, r),
                    BinaryOperator::Subtract   => format!("KsSub({}, {})", l, r),
                    BinaryOperator::Multiply   => format!("KsMul({}, {})", l, r),
                    BinaryOperator::Divide     => format!("KsDiv({}, {})", l, r),
                    BinaryOperator::Modulo     => format!("KsMod({}, {})", l, r),
                    BinaryOperator::Equal      => format!("KsEq({}, {})", l, r),
                    BinaryOperator::NotEqual   => format!("KsNeq({}, {})", l, r),
                    BinaryOperator::LessThan   => format!("KsLt({}, {})", l, r),
                    BinaryOperator::LessEqual  => format!("KsLe({}, {})", l, r),
                    BinaryOperator::GreaterThan => format!("KsGt({}, {})", l, r),
                    BinaryOperator::GreaterEqual => format!("KsGe({}, {})", l, r),
                    BinaryOperator::And => format!("(KsTruthy({}) && KsTruthy({}))", l, r),
                    BinaryOperator::Or  => format!("(KsTruthy({}) || KsTruthy({}))", l, r),
                }
            }
            Expr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand);
                match op {
                    UnaryOperator::Negate => format!("(-(double)({}))", o),
                    UnaryOperator::Not    => format!("(!KsTruthy({}))", o),
                }
            }
            Expr::FunctionCall { callee, args, .. } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                match callee.as_ref() {
                    Expr::Identifier { name, .. } => {
                        match name.as_str() {
                            "len"   => format!("KsLen({})", arg_strs.join(", ")),
                            "type"  => format!("KsType({})", arg_strs.join(", ")),
                            "str"   => format!("KsStr({})", arg_strs.join(", ")),
                            "push"  => format!("KsPush({})", arg_strs.join(", ")),
                            "print" => format!("KsPrint({})", arg_strs.join(", ")),
                            other   => format!("Ks_{}({})", other, arg_strs.join(", ")),
                        }
                    }
                    other => {
                        let callee_str = self.emit_expr(other);
                        format!("{}({})", callee_str, arg_strs.join(", "))
                    }
                }
            }
            Expr::MethodCall { object, method, args, .. } => {
                let obj = self.emit_expr(object);
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                // Emit as dynamic method call
                format!("((dynamic)({})).{}({})", obj, method, arg_strs.join(", "))
            }
            Expr::MemberAccess { object, member, .. } => {
                let obj = self.emit_expr(object);
                format!("((Dictionary<object,object>)({}))[\"{}\"]", obj, member)
            }
            Expr::Index { object, index, .. } => {
                let obj = self.emit_expr(object);
                let idx = self.emit_expr(index);
                format!("KsIndex({}, {})", obj, idx)
            }
            Expr::ListLiteral { elements, .. } => {
                let elems: Vec<String> = elements.iter().map(|e| self.emit_expr(e)).collect();
                format!("new List<object> {{ {} }}", elems.join(", "))
            }
            Expr::DictLiteral { entries, .. } => {
                if entries.is_empty() {
                    return "new Dictionary<object,object>()".to_string();
                }
                let pairs: Vec<String> = entries.iter().map(|(k, v)| {
                    format!("{{ {}, {} }}", self.emit_expr(k), self.emit_expr(v))
                }).collect();
                format!("new Dictionary<object,object> {{ {} }}", pairs.join(", "))
            }
            Expr::StringInterpolation { parts, .. } => {
                // Use C# string interpolation via concatenation
                let mut pieces: Vec<String> = Vec::new();
                for part in parts {
                    match part {
                        StringPart::Literal(s) => {
                            pieces.push(format!("\"{}\"",
                                s.replace('\\', "\\\\").replace('"', "\\\"")));
                        }
                        StringPart::Expression(expr) => {
                            pieces.push(format!("KsStr({})", self.emit_expr(expr)));
                        }
                    }
                }
                format!("({})", pieces.join(" + "))
            }
            Expr::New { class_name, args, .. } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("new {}({})", class_name, arg_strs.join(", "))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen_cs(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let program = parser.parse().unwrap();
        generate(&program)
    }

    #[test]
    fn test_cs_header() {
        let cs = gen_cs("print \"Hello\"");
        assert!(cs.contains("using System;"));
        assert!(cs.contains("class Program {"));
        assert!(cs.contains("static void Main(string[] args)"));
    }

    #[test]
    fn test_cs_print() {
        let cs = gen_cs(r#"print "Hello, World!""#);
        assert!(cs.contains("KsPrint(\"Hello, World!\")"));
    }

    #[test]
    fn test_cs_assignment() {
        let cs = gen_cs("x = 42");
        assert!(cs.contains("object x = (double)42"));
    }

    #[test]
    fn test_cs_function() {
        let cs = gen_cs("def greet(name) {\n  print name\n}");
        assert!(cs.contains("static object Ks_greet(object name)"));
        assert!(cs.contains("KsPrint(name)"));
    }

    #[test]
    fn test_cs_if_statement() {
        let cs = gen_cs("if x >= 5 {\n  print x\n}");
        assert!(cs.contains("if (KsTruthy(KsGe(x, (double)5)))"));
    }

    #[test]
    fn test_cs_while_loop() {
        let cs = gen_cs("while x < 10 {\n  x = x + 1\n}");
        assert!(cs.contains("while (KsTruthy(KsLt(x, (double)10)))"));
    }

    #[test]
    fn test_cs_for_loop() {
        let cs = gen_cs("for item in items {\n  print item\n}");
        assert!(cs.contains("foreach (object item in"));
    }

    #[test]
    fn test_cs_list_literal() {
        let cs = gen_cs(r#"x = ["a", "b"]"#);
        assert!(cs.contains("new List<object>"));
    }

    #[test]
    fn test_cs_dict_literal() {
        let cs = gen_cs(r#"x = {"name": "Bob"}"#);
        assert!(cs.contains("new Dictionary<object,object>"));
        assert!(cs.contains("\"name\""));
    }

    #[test]
    fn test_cs_string_interpolation() {
        let cs = gen_cs(r#"
            name = "Bob"
            print "Hi {$name}"
        "#);
        assert!(cs.contains("KsStr(name)"));
    }

    #[test]
    fn test_cs_try_catch() {
        let cs = gen_cs("try {\n  print 1\n} catch (err) {\n  print err\n}");
        assert!(cs.contains("try {"));
        assert!(cs.contains("} catch (Exception _ex_err) {"));
    }

    #[test]
    fn test_cs_return() {
        let cs = gen_cs("def add(a, b) {\n  return a + b\n}");
        assert!(cs.contains("return KsAdd(a, b)"));
    }

    #[test]
    fn test_cs_runtime_helpers() {
        let cs = gen_cs("print 1");
        assert!(cs.contains("static void KsPrint("));
        assert!(cs.contains("static bool KsTruthy("));
        assert!(cs.contains("static object KsAdd("));
    }

    #[test]
    fn test_cs_boolean_ops() {
        let cs = gen_cs("x = true and false");
        assert!(cs.contains("KsTruthy(true) && KsTruthy(false)"));
    }
}
