/// KelpyShark → Java Code Generator
///
/// Transpiles a KelpyShark AST into Java source code.
///
/// Strategy:
///   - All KelpyShark values are represented as `Object` (boxed Double, String, Boolean, null).
///   - A static runtime helper class is emitted at the top of the file.
///   - User-defined functions become static methods on the generated `Program` class.
///   - The top-level program runs in `main(String[] args)`.
///   - Classes become top-level inner static classes.

use crate::ast::*;

/// Generate a complete Java source file from a KelpyShark Program AST.
pub fn generate(program: &Program) -> String {
    let mut gen = JavaGenerator::new();
    gen.emit_program(program);
    gen.output
}

struct JavaGenerator {
    output: String,
    indent: usize,
}

impl JavaGenerator {
    fn new() -> Self {
        JavaGenerator {
            output: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, text: &str) {
        let indent_str = "    ".repeat(self.indent);
        self.output.push_str(&format!("{}{}\n", indent_str, text));
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    // ── Program ──────────────────────────────────────────────

    fn emit_program(&mut self, program: &Program) {
        self.line("// Generated by KelpyShark Compiler v0.1.0");
        self.line("import java.util.*;");
        self.blank();
        self.line("public class Program {");
        self.indent += 1;

        self.emit_runtime_helpers();
        self.blank();

        // Emit inner class definitions first
        for stmt in &program.statements {
            if let Statement::ClassDef { .. } = stmt {
                self.emit_statement(stmt);
                self.blank();
            }
        }

        // Emit user function definitions
        for stmt in &program.statements {
            if let Statement::FunctionDef { .. } = stmt {
                self.emit_statement(stmt);
                self.blank();
            }
        }

        // Emit main method
        self.line("public static void main(String[] args) throws Exception {");
        self.indent += 1;
        for stmt in &program.statements {
            match stmt {
                Statement::FunctionDef { .. } | Statement::ClassDef { .. } => continue,
                _ => self.emit_statement(stmt),
            }
        }
        self.indent -= 1;
        self.line("}");

        self.indent -= 1;
        self.line("}");
    }

    // ── Runtime helper methods ────────────────────────────────

    fn emit_runtime_helpers(&mut self) {
        // Print
        self.line("static void ksPrint(Object v) {");
        self.indent += 1;
        self.line("if (v instanceof Double) {");
        self.indent += 1;
        self.line("double d = (Double) v;");
        self.line("if (d == Math.floor(d) && !Double.isInfinite(d)) System.out.println((long) d);");
        self.line("else System.out.println(d);");
        self.indent -= 1;
        self.line("} else if (v == null) {");
        self.indent += 1;
        self.line("System.out.println(\"null\");");
        self.indent -= 1;
        self.line("} else {");
        self.indent += 1;
        self.line("System.out.println(v);");
        self.indent -= 1;
        self.line("}");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Truthiness
        self.line("static boolean ksTruthy(Object v) {");
        self.indent += 1;
        self.line("if (v == null) return false;");
        self.line("if (v instanceof Boolean) return (Boolean) v;");
        self.line("if (v instanceof Double) return (Double) v != 0.0;");
        self.line("if (v instanceof String) return !((String) v).isEmpty();");
        self.line("if (v instanceof List) return !((List<?>) v).isEmpty();");
        self.line("if (v instanceof Map) return !((Map<?,?>) v).isEmpty();");
        self.line("return true;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Add / concat
        self.line("@SuppressWarnings(\"unchecked\")");
        self.line("static Object ksAdd(Object a, Object b) {");
        self.indent += 1;
        self.line("if (a instanceof Double && b instanceof Double)");
        self.indent += 1;
        self.line("return (Double) a + (Double) b;");
        self.indent -= 1;
        self.line("// string coercion");
        self.line("return ksStr(a) + ksStr(b);");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Arithmetic helpers
        self.line("static Object ksSub(Object a, Object b) { return (Double)a - (Double)b; }");
        self.line("static Object ksMul(Object a, Object b) { return (Double)a * (Double)b; }");
        self.line("static Object ksDiv(Object a, Object b) { return (Double)a / (Double)b; }");
        self.line("static Object ksMod(Object a, Object b) { return (Double)a % (Double)b; }");
        self.blank();

        // Comparison
        self.line("static Object ksEq(Object a, Object b) {");
        self.indent += 1;
        self.line("if (a == null && b == null) return true;");
        self.line("if (a == null || b == null) return false;");
        self.line("return a.equals(b);");
        self.indent -= 1;
        self.line("}");
        self.line("static Object ksNeq(Object a, Object b) { return !(Boolean)ksEq(a,b); }");
        self.line("static Object ksLt(Object a, Object b)  { return (Double)a < (Double)b; }");
        self.line("static Object ksLe(Object a, Object b)  { return (Double)a <= (Double)b; }");
        self.line("static Object ksGt(Object a, Object b)  { return (Double)a > (Double)b; }");
        self.line("static Object ksGe(Object a, Object b)  { return (Double)a >= (Double)b; }");
        self.blank();

        // Type conversion
        self.line("static String ksStr(Object v) {");
        self.indent += 1;
        self.line("if (v == null) return \"null\";");
        self.line("if (v instanceof Double) {");
        self.indent += 1;
        self.line("double d = (Double) v;");
        self.line("if (d == Math.floor(d) && !Double.isInfinite(d)) return String.valueOf((long)d);");
        self.line("return String.valueOf(d);");
        self.indent -= 1;
        self.line("}");
        self.line("return v.toString();");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // len()
        self.line("static Object ksLen(Object v) {");
        self.indent += 1;
        self.line("if (v instanceof String) return (double)((String)v).length();");
        self.line("if (v instanceof List) return (double)((List<?>)v).size();");
        self.line("if (v instanceof Map) return (double)((Map<?,?>)v).size();");
        self.line("throw new RuntimeException(\"len() not supported for \" + v.getClass().getSimpleName());");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // type()
        self.line("static Object ksType(Object v) {");
        self.indent += 1;
        self.line("if (v == null) return \"null\";");
        self.line("if (v instanceof Double) return \"number\";");
        self.line("if (v instanceof String) return \"string\";");
        self.line("if (v instanceof Boolean) return \"boolean\";");
        self.line("if (v instanceof List) return \"list\";");
        self.line("if (v instanceof Map) return \"dict\";");
        self.line("return \"object\";");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // push()
        self.line("@SuppressWarnings(\"unchecked\")");
        self.line("static Object ksPush(Object list, Object val) {");
        self.indent += 1;
        self.line("List<Object> copy = new ArrayList<>((List<Object>)list);");
        self.line("copy.add(val);");
        self.line("return copy;");
        self.indent -= 1;
        self.line("}");
        self.blank();

        // Index access
        self.line("@SuppressWarnings(\"unchecked\")");
        self.line("static Object ksIndex(Object obj, Object idx) {");
        self.indent += 1;
        self.line("if (obj instanceof List) return ((List<Object>)obj).get((int)(double)(Double)idx);");
        self.line("if (obj instanceof Map) return ((Map<Object,Object>)obj).get(idx);");
        self.line("if (obj instanceof String) return String.valueOf(((String)obj).charAt((int)(double)(Double)idx));");
        self.line("throw new RuntimeException(\"Cannot index \" + ksType(obj));");
        self.indent -= 1;
        self.line("}");
    }

    // ── Statements ────────────────────────────────────────────

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Assignment { name, value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("Object {} = {};", name, v));
            }
            Statement::CompoundAssignment { name, op, value, .. } => {
                let v = self.emit_expr(value);
                let helper = match op {
                    CompoundOp::Add      => "ksAdd",
                    CompoundOp::Subtract => "ksSub",
                    CompoundOp::Multiply => "ksMul",
                    CompoundOp::Divide   => "ksDiv",
                };
                self.line(&format!("{} = {}({}, {});", name, helper, name, v));
            }
            Statement::FunctionDef { name, params, body, .. } => {
                let param_list = params
                    .iter()
                    .map(|p| format!("Object {}", p))
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(&format!("static Object ks_{}({}) throws Exception {{", name, param_list));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.line("return null;");
                self.indent -= 1;
                self.line("}");
            }
            Statement::If { condition, then_body, else_body, .. } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("if (ksTruthy({})) {{", cond));
                self.indent += 1;
                for s in then_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::While { condition, body, .. } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("while (ksTruthy({})) {{", cond));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::For { variable, iterable, body, .. } => {
                let iter = self.emit_expr(iterable);
                self.line(&format!("for (Object {} : (Iterable<?>){}) {{", variable, iter));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::Return { value, .. } => {
                let val = match value {
                    Some(expr) => self.emit_expr(expr),
                    None => "null".to_string(),
                };
                self.line(&format!("return {};", val));
            }
            Statement::Break { .. }    => self.line("break;"),
            Statement::Continue { .. } => self.line("continue;"),
            Statement::Print { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("ksPrint({});", v));
            }
            Statement::ExprStatement { expr, .. } => {
                let e = self.emit_expr(expr);
                self.line(&format!("{};", e));
            }
            Statement::Import { module, .. } => {
                // Emit as comment — Java imports are handled at compile time
                self.line(&format!("// import {}", module));
            }
            Statement::Throw { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("throw new RuntimeException(ksStr({}));", v));
            }
            Statement::TryCatch { try_body, catch_var, catch_body, .. } => {
                self.line("try {");
                self.indent += 1;
                for s in try_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line(&format!("}} catch (Exception {}) {{", catch_var));
                self.indent += 1;
                // Expose catch variable as Object (its message string)
                self.line(&format!(
                    "Object {} = {}.getMessage() != null ? {}.getMessage() : {}.toString();",
                    catch_var, catch_var, catch_var, catch_var
                ));
                for s in catch_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::ClassDef { name, methods, .. } => {
                self.line(&format!("static class {} {{", name));
                self.indent += 1;
                for m in methods {
                    self.emit_statement(m);
                }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    // ── Expressions ───────────────────────────────────────────

    fn emit_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::NumberLiteral { value, .. } => {
                if *value == (*value as i64) as f64 {
                    format!("(double){}", *value as i64)
                } else {
                    format!("{}", value)
                }
            }
            Expr::StringLiteral { value, .. } => {
                format!("\"{}\"",
                    value.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::BooleanLiteral { value, .. } => format!("{}", value),
            Expr::NullLiteral { .. } => "null".to_string(),
            Expr::Identifier { name, .. } => name.clone(),
            Expr::BinaryOp { left, op, right, .. } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                match op {
                    BinaryOperator::Add        => format!("ksAdd({}, {})", l, r),
                    BinaryOperator::Subtract   => format!("ksSub({}, {})", l, r),
                    BinaryOperator::Multiply   => format!("ksMul({}, {})", l, r),
                    BinaryOperator::Divide     => format!("ksDiv({}, {})", l, r),
                    BinaryOperator::Modulo     => format!("ksMod({}, {})", l, r),
                    BinaryOperator::Equal      => format!("ksEq({}, {})", l, r),
                    BinaryOperator::NotEqual   => format!("ksNeq({}, {})", l, r),
                    BinaryOperator::LessThan   => format!("ksLt({}, {})", l, r),
                    BinaryOperator::LessEqual  => format!("ksLe({}, {})", l, r),
                    BinaryOperator::GreaterThan => format!("ksGt({}, {})", l, r),
                    BinaryOperator::GreaterEqual => format!("ksGe({}, {})", l, r),
                    BinaryOperator::And => format!("(ksTruthy({}) && ksTruthy({}))", l, r),
                    BinaryOperator::Or  => format!("(ksTruthy({}) || ksTruthy({}))", l, r),
                }
            }
            Expr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand);
                match op {
                    UnaryOperator::Negate => format!("(-(Double)({})) ", o),
                    UnaryOperator::Not    => format!("(!ksTruthy({}))", o),
                }
            }
            Expr::FunctionCall { callee, args, .. } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                match callee.as_ref() {
                    Expr::Identifier { name, .. } => {
                        match name.as_str() {
                            "len"   => format!("ksLen({})", arg_strs.join(", ")),
                            "type"  => format!("ksType({})", arg_strs.join(", ")),
                            "str"   => format!("ksStr({})", arg_strs.join(", ")),
                            "push"  => format!("ksPush({})", arg_strs.join(", ")),
                            "print" => format!("ksPrint({})", arg_strs.join(", ")),
                            other   => format!("ks_{}({})", other, arg_strs.join(", ")),
                        }
                    }
                    other => {
                        let callee_str = self.emit_expr(other);
                        format!("{}({})", callee_str, arg_strs.join(", "))
                    }
                }
            }
            Expr::MethodCall { object, method, args, .. } => {
                let obj = self.emit_expr(object);
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("((Object){}).getClass().getMethod(\"{}\").invoke({}, {})",
                    obj, method, obj, arg_strs.join(", "))
            }
            Expr::MemberAccess { object, member, .. } => {
                let obj = self.emit_expr(object);
                // Use map key access for dicts; otherwise generate a comment
                format!("((Map<Object,Object>)({})).get(\"{}\")", obj, member)
            }
            Expr::Index { object, index, .. } => {
                let obj = self.emit_expr(object);
                let idx = self.emit_expr(index);
                format!("ksIndex({}, {})", obj, idx)
            }
            Expr::ListLiteral { elements, .. } => {
                let elems: Vec<String> = elements.iter().map(|e| self.emit_expr(e)).collect();
                format!(
                    "new ArrayList<>(Arrays.asList({}))",
                    elems.join(", ")
                )
            }
            Expr::DictLiteral { entries, .. } => {
                if entries.is_empty() {
                    return "new LinkedHashMap<>()".to_string();
                }
                let mut parts = vec!["new LinkedHashMap<Object,Object>() {{ ".to_string()];
                for (k, v) in entries {
                    let key = self.emit_expr(k);
                    let val = self.emit_expr(v);
                    parts.push(format!("put({}, {}); ", key, val));
                }
                parts.push("}}".to_string());
                parts.join("")
            }
            Expr::StringInterpolation { parts, .. } => {
                // Build via StringBuilder
                let mut result = String::from("(");
                let mut first = true;
                for part in parts {
                    if !first {
                        result.push_str(" + ");
                    }
                    first = false;
                    match part {
                        StringPart::Literal(s) => {
                            result.push_str(&format!("\"{}\"",
                                s.replace('\\', "\\\\").replace('"', "\\\"")));
                        }
                        StringPart::Expression(expr) => {
                            result.push_str(&format!("ksStr({})", self.emit_expr(expr)));
                        }
                    }
                }
                result.push(')');
                result
            }
            Expr::New { class_name, args, .. } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("new {}({})", class_name, arg_strs.join(", "))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen_java(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let program = parser.parse().unwrap();
        generate(&program)
    }

    #[test]
    fn test_java_header() {
        let java = gen_java("print \"Hello\"");
        assert!(java.contains("public class Program"));
        assert!(java.contains("public static void main(String[] args)"));
        assert!(java.contains("import java.util.*"));
    }

    #[test]
    fn test_java_print() {
        let java = gen_java(r#"print "Hello, World!""#);
        assert!(java.contains("ksPrint(\"Hello, World!\")"));
    }

    #[test]
    fn test_java_assignment() {
        let java = gen_java("x = 42");
        assert!(java.contains("Object x = (double)42"));
    }

    #[test]
    fn test_java_function() {
        let java = gen_java("def greet(name) {\n  print name\n}");
        assert!(java.contains("static Object ks_greet(Object name)"));
        assert!(java.contains("ksPrint(name)"));
    }

    #[test]
    fn test_java_if_statement() {
        let java = gen_java("if x >= 5 {\n  print x\n}");
        assert!(java.contains("if (ksTruthy(ksGe(x, (double)5)))"));
    }

    #[test]
    fn test_java_while_loop() {
        let java = gen_java("while x < 10 {\n  x = x + 1\n}");
        assert!(java.contains("while (ksTruthy(ksLt(x, (double)10)))"));
    }

    #[test]
    fn test_java_for_loop() {
        let java = gen_java("for item in items {\n  print item\n}");
        assert!(java.contains("for (Object item : (Iterable<?>)items)"));
    }

    #[test]
    fn test_java_list_literal() {
        let java = gen_java(r#"x = ["a", "b"]"#);
        assert!(java.contains("new ArrayList<>(Arrays.asList("));
    }

    #[test]
    fn test_java_string_interpolation() {
        let java = gen_java(r#"
            name = "Bob"
            print "Hi {$name}"
        "#);
        assert!(java.contains("ksStr(name)"));
    }

    #[test]
    fn test_java_return() {
        let java = gen_java("def add(a, b) {\n  return a + b\n}");
        assert!(java.contains("return ksAdd(a, b)"));
    }

    #[test]
    fn test_java_try_catch() {
        let java = gen_java("try {\n  print 1\n} catch (err) {\n  print err\n}");
        assert!(java.contains("try {"));
        assert!(java.contains("} catch (Exception err) {"));
    }

    #[test]
    fn test_java_boolean_ops() {
        let java = gen_java("x = true and false");
        assert!(java.contains("ksTruthy(true) && ksTruthy(false)"));
    }

    #[test]
    fn test_java_runtime_helpers() {
        let java = gen_java("print 1");
        assert!(java.contains("static void ksPrint("));
        assert!(java.contains("static boolean ksTruthy("));
        assert!(java.contains("static Object ksAdd("));
    }
}
