/// KelpyShark → JavaScript Code Generator
///
/// Transpiles a KelpyShark AST into JavaScript source code.
/// The generated JS runs in Node.js or browsers.

use crate::ast::*;

/// Generate a complete JavaScript source file from a KelpyShark Program AST.
pub fn generate(program: &Program) -> String {
    let mut gen = JsGenerator::new();
    gen.emit_program(program);
    gen.output
}

struct JsGenerator {
    output: String,
    indent: usize,
}

impl JsGenerator {
    fn new() -> Self {
        JsGenerator {
            output: String::new(),
            indent: 0,
        }
    }

    fn line(&mut self, text: &str) {
        let indent_str = "  ".repeat(self.indent);
        self.output.push_str(&format!("{}{}\n", indent_str, text));
    }

    fn blank(&mut self) {
        self.output.push('\n');
    }

    fn emit_program(&mut self, program: &Program) {
        self.line("// Generated by KelpyShark Compiler v0.1.0");
        self.line("\"use strict\";");
        self.blank();

        for stmt in &program.statements {
            self.emit_statement(stmt);
        }
    }

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Assignment { name, value, .. } => {
                let expr = self.emit_expr(value);
                self.line(&format!("let {} = {};", name, expr));
            }
            Statement::FunctionDef {
                name,
                params,
                body,
                ..
            } => {
                self.line(&format!(
                    "function {}({}) {{",
                    name,
                    params.join(", ")
                ));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
                self.blank();
            }
            Statement::If {
                condition,
                then_body,
                else_body,
                ..
            } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("if ({}) {{", cond));
                self.indent += 1;
                for s in then_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                if let Some(else_stmts) = else_body {
                    self.line("} else {");
                    self.indent += 1;
                    for s in else_stmts {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                }
                self.line("}");
            }
            Statement::While {
                condition, body, ..
            } => {
                let cond = self.emit_expr(condition);
                self.line(&format!("while ({}) {{", cond));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::For {
                variable,
                iterable,
                body,
                ..
            } => {
                let iter = self.emit_expr(iterable);
                self.line(&format!("for (let {} of {}) {{", variable, iter));
                self.indent += 1;
                for s in body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Statement::Return { value, .. } => {
                let val = match value {
                    Some(expr) => self.emit_expr(expr),
                    None => "undefined".to_string(),
                };
                self.line(&format!("return {};", val));
            }
            Statement::Print { value, .. } => {
                let expr = self.emit_expr(value);
                self.line(&format!("console.log({});", expr));
            }
            Statement::ExprStatement { expr, .. } => {
                let e = self.emit_expr(expr);
                self.line(&format!("{};", e));
            }
            Statement::Import { module, .. } => {
                // Convert dotted import to require
                let path = module.replace('.', "/");
                let alias = module.replace('.', "_");
                self.line(&format!(
                    "const {} = require(\"{}\");",
                    alias, path
                ));
            }
            Statement::Break { .. } => self.line("break;"),
            Statement::Continue { .. } => self.line("continue;"),
            Statement::Throw { value, .. } => {
                let v = self.emit_expr(value);
                self.line(&format!("throw {};", v));
            }
            Statement::TryCatch { try_body, catch_var, catch_body, .. } => {
                self.line("try {");
                self.indent += 1;
                for s in try_body { self.emit_statement(s); }
                self.indent -= 1;
                let var = catch_var.as_str();
                self.line(&format!("}} catch ({}) {{", var));
                self.indent += 1;
                for s in catch_body { self.emit_statement(s); }
                self.indent -= 1;
                self.line("}");
            }
            Statement::CompoundAssignment { name, op, value, .. } => {
                let v = self.emit_expr(value);
                let js_op = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Subtract => "-=",
                    CompoundOp::Multiply => "*=",
                    CompoundOp::Divide => "/=",
                };
                self.line(&format!("{} {} {};", name, js_op, v));
            }
            Statement::ClassDef { name, methods, .. } => {
                self.line(&format!("class {} {{", name));
                self.indent += 1;
                for m in methods { self.emit_statement(m); }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    fn emit_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::NumberLiteral { value, .. } => {
                if *value == (*value as i64) as f64 {
                    format!("{}", *value as i64)
                } else {
                    format!("{}", value)
                }
            }
            Expr::StringLiteral { value, .. } => {
                format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::BooleanLiteral { value, .. } => {
                format!("{}", value)
            }
            Expr::Identifier { name, .. } => name.clone(),
            Expr::BinaryOp {
                left, op, right, ..
            } => {
                let l = self.emit_expr(left);
                let r = self.emit_expr(right);
                let js_op = match op {
                    BinaryOperator::Add => "+",
                    BinaryOperator::Subtract => "-",
                    BinaryOperator::Multiply => "*",
                    BinaryOperator::Divide => "/",
                    BinaryOperator::Modulo => "%",
                    BinaryOperator::Equal => "===",
                    BinaryOperator::NotEqual => "!==",
                    BinaryOperator::LessThan => "<",
                    BinaryOperator::LessEqual => "<=",
                    BinaryOperator::GreaterThan => ">",
                    BinaryOperator::GreaterEqual => ">=",
                    BinaryOperator::And => "&&",
                    BinaryOperator::Or => "||",
                };
                format!("({} {} {})", l, js_op, r)
            }
            Expr::UnaryOp { op, operand, .. } => {
                let o = self.emit_expr(operand);
                match op {
                    UnaryOperator::Negate => format!("(- {})", o),
                    UnaryOperator::Not => format!("(! {})", o),
                }
            }
            Expr::FunctionCall { callee, args, .. } => {
                let func = self.emit_expr(callee);
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("{}({})", func, arg_strs.join(", "))
            }
            Expr::Index {
                object, index, ..
            } => {
                let obj = self.emit_expr(object);
                let idx = self.emit_expr(index);
                format!("{}[{}]", obj, idx)
            }
            Expr::MemberAccess {
                object, member, ..
            } => {
                let obj = self.emit_expr(object);
                format!("{}.{}", obj, member)
            }
            Expr::ListLiteral { elements, .. } => {
                let elems: Vec<String> = elements.iter().map(|e| self.emit_expr(e)).collect();
                format!("[{}]", elems.join(", "))
            }
            Expr::DictLiteral { entries, .. } => {
                let pairs: Vec<String> = entries
                    .iter()
                    .map(|(k, v)| format!("{}: {}", self.emit_expr(k), self.emit_expr(v)))
                    .collect();
                format!("{{{}}}", pairs.join(", "))
            }
            Expr::StringInterpolation { parts, .. } => {
                // Use JS template literals
                let mut result = String::from("`");
                for part in parts {
                    match part {
                        StringPart::Literal(s) => result.push_str(s),
                        StringPart::Expression(expr) => {
                            result.push_str("${");
                            result.push_str(&self.emit_expr(expr));
                            result.push('}');
                        }
                    }
                }
                result.push('`');
                result
            }
            Expr::NullLiteral { .. } => "null".to_string(),
            Expr::MethodCall { object, method, args, .. } => {
                let obj = self.emit_expr(object);
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("{}.{}({})", obj, method, arg_strs.join(", "))
            }
            Expr::New { class_name, args, .. } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.emit_expr(a)).collect();
                format!("new {}({})", class_name, arg_strs.join(", "))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::Lexer;
    use crate::parser::Parser;

    fn gen_js(source: &str) -> String {
        let mut lexer = Lexer::new(source);
        let tokens = lexer.tokenize().unwrap();
        let mut parser = Parser::new(tokens);
        let program = parser.parse().unwrap();
        generate(&program)
    }

    #[test]
    fn test_js_print() {
        let js = gen_js(r#"print "Hello""#);
        assert!(js.contains("console.log(\"Hello\")"));
    }

    #[test]
    fn test_js_assignment() {
        let js = gen_js("x = 42");
        assert!(js.contains("let x = 42;"));
    }

    #[test]
    fn test_js_function() {
        let js = gen_js("def greet(name) {\n  print name\n}");
        assert!(js.contains("function greet(name)"));
        assert!(js.contains("console.log(name)"));
    }

    #[test]
    fn test_js_if_statement() {
        let js = gen_js("if x >= 5 {\n  print x\n}");
        assert!(js.contains("if ((x >= 5))"));
    }

    #[test]
    fn test_js_for_loop() {
        let js = gen_js("for item in items {\n  print item\n}");
        assert!(js.contains("for (let item of items)"));
    }

    #[test]
    fn test_js_list_literal() {
        let js = gen_js(r#"x = ["a", "b", "c"]"#);
        assert!(js.contains("[\"a\", \"b\", \"c\"]"));
    }

    #[test]
    fn test_js_dict_literal() {
        let js = gen_js(r#"x = {"name": "Bob"}"#);
        assert!(js.contains("\"name\": \"Bob\""));
    }

    #[test]
    fn test_js_string_interpolation() {
        let js = gen_js(r#"x = "Hello {$name}!""#);
        assert!(js.contains("`Hello ${name}!`"));
    }

    #[test]
    fn test_js_strict_mode() {
        let js = gen_js("x = 1");
        assert!(js.contains("\"use strict\""));
    }

    #[test]
    fn test_js_import() {
        let js = gen_js("import http.server");
        assert!(js.contains("require(\"http/server\")"));
    }

    #[test]
    fn test_js_boolean_ops() {
        let js = gen_js("x = true and false");
        assert!(js.contains("&&"));
    }

    #[test]
    fn test_js_index_access() {
        let js = gen_js("x = list[0]");
        assert!(js.contains("list[0]"));
    }
}
